name: HiPeaksol_SMP
version: ${project.version}
main: fengli.playerreload.PlayerReload
api-version: 1.16
authors: [Fengli_ruomeng]
softdepend: [ProtocolLib]
description: HiPeaksol_SMP Plugin
commands:
  food:
    description: No can use data
  getfuckingop:
    description: No can use data
  SetHP:
    description: No can use data
  report:
    description: No can use data
  shoutL:
    description: Shout L;
  EditItem:
    description: [TestUse] Edit Item On You Hand!.
  ReportMenu:
    description: No things.
